//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int ChiTietID { get; set; }
        public int DonHangID { get; set; }
        public int MonAnID { get; set; }
        public int SoLuong { get; set; }
        public int Gia { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual MonAn MonAn { get; set; }
    }
}
